############################################################
#
# Send Notification when Electricity Voltage is High
#
############################################################

- alias: NOTIFY when Electricity Supply Voltage is HIGH
  trigger: 
    platform: numeric_state
    entity_id: sensor.ups_input_voltage 
    above: 253
  action:
    service: notify.notify_all
    data_template:
      title: 'Electricity Supply Voltage High'
      message: >
        Electricity Voltage High: {{ states('sensor.ups_input_voltage') }} Volts 

############################################################
#
# Send Notification when Electricity Voltage is Low
#
############################################################

- alias: NOTIFY when Electricity Supply Voltage is LOW
  trigger: 
    platform: numeric_state
    entity_id: sensor.ups_input_voltage 
    below: 230
  action:
    service: notify.notify_all
    data_template:
      title: 'Electricity Supply Voltage Low'
      message: >
        Electricity Voltage Low: {{ states('sensor.ups_input_voltage') }} Volts 
