############################################################
#
# Home Assistant CCTV Package
#
############################################################

automation:
  ############################################################
  # CCTV Detection Controls
  ############################################################

  # Get CCTV Intrusion Detection Status

  - alias: GET Intrusion Detection STATUS
    trigger:
      platform: state
      entity_id: input_boolean.cctv_disabled
      state: 'on'
    condition:
      condition: state
      entity_id: switch.cctv_intrusion_detection
      state: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: script.get_intrusion_detection

  # Get CCTV Line Detection Status

  - alias: GET Line Detection STATUS
    trigger:
      platform: state
      entity_id: input_boolean.cctv_disabled
      state: 'on'
    condition:
      condition: state
      entity_id: switch.cctv_line_crossing_detection
      state: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: script.get_line_detection

  # Get CCTV Motion Detection Status

  - alias: GET Motion Detection STATUS
    trigger:
      platform: state
      entity_id: input_boolean.cctv_disabled
      state: 'on'
    condition:
      condition: state
      entity_id: switch.cctv_motion
      state: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: script.get_motion

  # Set CCTV Intrusion Detection Status

  - alias: SET Intrusion Detection STATUS
    trigger:
      platform: state
      entity_id: input_boolean.cctv_disabled
      state: 'off'
    condition:
      condition: state
      entity_id: input_boolean.cctv_intruder
      state: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: script.set_intrusion_detection

  # Set CCTV Line Detection Status

  - alias: SET Line Detection STATUS
    trigger:
      platform: state
      entity_id: input_boolean.cctv_disabled
      state: 'off'
    condition:
      condition: state
      entity_id: input_boolean.cctv_line
      state: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: script.set_line_detection

  # Set CCTV Motion Detection Status

  - alias: SET Motion Detection STATUS
    trigger:
      platform: state
      entity_id: input_boolean.cctv_disabled
      state: 'off'
    condition:
      condition: state
      entity_id: input_boolean.cctv_motion
      state: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: script.set_motion

  ############################################################
  #
  # Home Assistant Turn off CCTV Detection when
  #
  # Front Door is Open Automation
  #
  ############################################################

  - alias: Set CCTV Detection to OFF when Front Door OPEN
    trigger:
      platform: state
      entity_id: binary_sensor.frontdoorswitch_sensor_3_0
      state: 'on'
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.cctv_disabled

  ############################################################
  #
  # Home Assistant Turn off CCTV Detection when
  #
  # Front Door is Open Automation
  #
  ############################################################

  - alias: Set CCTV Detection to ON when Front Door CLOSED
    trigger:
      platform: state
      entity_id: binary_sensor.frontdoorswitch_sensor_3_0
      state: 'off'
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.cctv_disabled

############################################################
#
# CCTV Helper Scripts
#
############################################################

script:

  # Turn CCTV Motion Detection Off

  cctv_motion_off:
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id: group.cctv

  # Store CCTV Motion Detection Settings

  get_intrusion_detection:
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.cctv_intruder
      - service: switch.turn_off
        data:
          entity_id: switch.cctv_intrusion_detection

  get_line_detection:
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.cctv_line
      - service: switch.turn_off
        data:
          entity_id:  switch.cctv_line_crossing_detection

  get_motion:
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.cctv_motion
      - service: switch.turn_off
        data:
          entity_id: switch.cctv_intrusion_detection

  # Restore CCTV Motion Detection Settings

  set_intrusion_detection:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.cctv_intrusion_detection
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.cctv_intruder

  set_line_detection:
    sequence:
      - service: switch.turn_on
        data:
          entity_id:  switch.cctv_line_crossing_detection
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.cctv_line
          
  set_motion:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.cctv_intrusion_detection
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.cctv_motion

############################################################
#
# CCTV Switches
#
############################################################

switch:
  - platform: mqtt
    name: "CCTV Motion"
    state_topic: "house/cctv/1/motion"
    command_topic: "house/cctv/1/motion/set"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "CCTV Intrusion Detection"
    state_topic: "house/cctv/1/intrusion"
    command_topic: "house/cctv/1/intrusion/set"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "CCTV Line Crossing Detection"
    state_topic: "house/cctv/1/line"
    command_topic: "house/cctv/1/line/set"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

############################################################
#
# CCTV Input Booleans
#
############################################################

input_boolean:
  cctv_line:
    name: CCTV Line
    initial: off

  cctv_intruder:
    name: CCTV Intruder
    initial: off

  cctv_motion:
    name: CCTV Motion
    initial: off

  cctv_disabled:
    name: CCTV Disabled
    initial: off
