############################################################
#
# Darksky Sensor
#
############################################################

- platform: darksky
  api_key: !secret darksky_api_key 
  monitored_conditions:
    - precip_type
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - wind_bearing
    - pressure
    - visibility
    - daily_summary
  units: uk2
